language: node_js
node_js:
- lts/carbon
- lts/dubnium
- stable
cache:
  directories:
  - node_modules
after_success:
- cat test/coverage/lcov.info | node_modules\.bin\coveralls
deploy:
  provider: npm
  email: robert.kleger@bobb.io
  skip_cleanup: true
  on:
    tags: true
    branch: master
  api_key: $NPM_TOKEN
