language: node_js
node_js:
- lts/carbon
- lts/dubnium
- stable
cache:
  directories:
  - node_modules
after_success:
- cat test/coverage/lcov.info | node_modules\.bin\coveralls
deploy:
  provider: npm
  email: robert.kleger@bobb.io
  on:
    tags: true
    branch: master
  api_key:
    secure: GXmJn3gQPmH5UUUv+BJ6ryKqfkKLTD+CaVdZeTzT7jKCgV4pOlW2GmStLaVA8aFxPsGR2ppkUlV7aaSiDTULV3xAMaHU5fa5dPcYijI5PU2W0NJrFY7e73O4EDS+PzN5D878liaKfS8XVLOcnvN1jNZ5sDqLZmRTgw7+16DTWIKAkOBp2J2bhJ9/CbsktngQxi95Ut6v6Wnzw71UiPPGUXTnxhKmQLRtdx+Ycz1GFiBNxD8BTT8qwGWmYJU9hPYyjHsuSF3I+hJtLvLE49rmH5maWv9LqnrGCUcKwrT9zrI5Vz7wzQ5SFxQuWfK6mr445mrgaKVC/X7U3lhYt9mMTm76+YpdySY+voVYTTGTbz9NFSpXJc0NxX9vjk1N62/L9KLg+QwcRunHF+f0kzY7inOP5ZvoFVDNFJCxztMkH34ws4wwcHysy0sXJ5umkZwjuXedg6zyoxDtwaeBbxChv40TTtTjAdxQSO1CK1iV3p0QaRqJOO8o9BneiqWQqMqElPFysApo1EiTxINBbgxy5BCIL11yNgGY/pJtqjJyNUTK6Y8uO6Jtso0ziZvj3RBNMdr0DlkWUwfrxfA4InqdTqsfdAvO3WmHxPRUpRtdDrZzy7MdsdmJqxZn5gf/m74AtHXhFzaWv7N7Ld/WnY9S4WAs+O6VJcqr8IU3q3DZHRA=
